name: suvido_eshop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # functionality
  fpdart: ^1.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  http: ^1.2.2
  get_it: ^8.0.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  encrypt: ^5.0.3
  # hive: ^2.2.3

  # ui
  shimmer: ^3.0.0
  salomon_bottom_bar: ^3.3.2
  cupertino_icons: ^1.0.8
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  
  uses-material-design: true

  assets:
    - lib/shared/assets/img/
  fonts: 
    - family: Merriweather
      fonts: 
        - asset: lib/shared/assets/fonts/Merriweather-Regular.ttf
          style: normal
          weight: 400
        - asset: lib/shared/assets/fonts/Merriweather-Light.ttf
          style: normal
          weight: 200
        - asset: lib/shared/assets/fonts/Merriweather-Italic.ttf
          style: italic
        - asset: lib/shared/assets/fonts/Merriweather-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/shared/assets/fonts/Merriweather-Bold.ttf
          style: normal
          weight: 700
      
      
